# This is a basic workflow to help you get started with Actions
name: Manual Deployment

# Controls when the action will run.
on:
  workflow_dispatch:
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dev-promote:
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'uat' }}
    name: uat
    # Utilizing the dynamic yml file for reusability
    uses: ./.github/workflows/deployment-workflow.yml
    with:
      WORKFLOW_TYPE: DEPLOYMENT
      AUTH_ORG_ALIAS: uat
    secrets:
      SECRET_URL_PATH: ${{ secrets.COE_PREDEMO_ORG_AUTH_URL}}
      DOCKER_HUB_UN: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PW: ${{ secrets.DOCKER_HUB_PASSWORD }}

  # Job to deploy components to the PREPROD environment
  prod-promote:
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'preprod' }}
    name: preprod
    # Utilizing the dynamic yml file for reusability
    uses: ./.github/workflows/deployment-workflow.yml
    with:
      WORKFLOW_TYPE: DEPLOYMENT
      AUTH_ORG_ALIAS: preprod
    secrets:
      #PROD_ORG_DOMAIN: ${{ secrets.PROD_ORG_DOMAIN }}
      SECRET_URL_PATH: ${{ secrets.COE_DEMO_ORG_AUTH_URL}}
      DOCKER_HUB_UN: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PW: ${{ secrets.DOCKER_HUB_PASSWORD }}
