# Pull request validation initiation
name: Pull Request (PR) Validation

# Controls when the action will run.
on:
  # Trigger the PR validation on pull request with master branch
  pull_request:
    branches:
      - "predemo"
      - "demo"
jobs:
  # Validate the Commit against Ci Org to ensure nothing is conflicting.
  build:
    name: PR Validation
    # Utilizing the dynamic yml file for reusability
    uses: ./.github/workflows/pr-validation-workflow.yml
    with:
      WORKFLOW_TYPE: PRVALIDATION
      AUTH_ORG_ALIAS: ci
      BASE_BRANCH: ${{ github.base_ref }}
    secrets:
      SECRET_URL_PATH: ${{secrets.COE_CI_ORG_AUTH_URL}}
      DOCKER_HUB_UN: ${{secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_PW: ${{secrets.DOCKER_HUB_PASSWORD}}
